### ISSUE TITLE
Start all plot not working ?

### ISSUE THREAD

**Issue by vanlongme** [kostya12071/chia#1]
I have filled up the requirement parameter but after run this script, no thing happend, no process at task manager ?

**Comment by lionB777** [comment]
try to change the log location to another location but the c:/ root, something like the desktop. you can do it in the startplotting script file, and run the shell as an administrator. It worked for me.

**Comment by kostya12071** [comment]
Are you calling script from PowerShell command-line? Can you provide the screenshot the parameters?  When working, script will spawn multiple PowerShell instances with "waiting" title.  Are you seeing any of that occurring?
