### ISSUE TITLE
Script Making Destination Folder Hidden?

### ISSUE THREAD

**Issue by XxViper06xX** [kostya12071/chia#10]
Is anyone else having an issue where after running the script the destination folder is being changed to hidden?

I've been doing some testing so I have had to stop and restart the script on several occasions. I save my plots to a \Plots\ folder. After I go and uncheck the hidden box in the folder properties all is good but sometime after restarting the script it gets hidden again. This has happened on multiple occasions to different folders on different HDDs.

Windows 10 Pro
E5-2699v3

Moving from temp SSD to HDD storage:

# Chia Plotting Automation Script 
# by Kostya

<#
    Simple robocopy command to move files from source to destination in a continous process
    Modify as follows:

    .\chia2drive.ps1 d:\ f:\ c:\scripts\filelog.log

#>

param (
    [Parameter(Mandatory=$true)][string]$tempPath,
    [Parameter(Mandatory=$true)][string]$plotPath,
	[string]$log = "c:\log\chia2drive.log"
)

robocopy $tempPath $plotPath *.plot /J /MOV /MOT:15 /LOG+:$log /TEE

**Comment by sin-inn** [comment]
I have got the same issue. Did you find a solution?

**Comment by XxViper06xX** [comment]
> I have got the same issue. Did you find a solution?

Not yet

**Comment by weblink-hr** [comment]
When copying from the root directory of a drive to a folder (non-root directory on a different drive), this can happen.
RoboCopy may set the new directory to hidden, as it copies the system attribute of the root folder of the drive over to the new folder.

You can prevent the new directory from becoming hidden by adding the /A-:SH option/flag/switch to your robocopy command.

If you already copied the directory without the /A-:SH option, running the command (`attrib -h  -s  -a [ Drive : ][ Path ]`) will fix the issue by unhiding the directory. 

So, in your case that would be:  `attrib -h -s -a D:/Plots`
