### ISSUE TITLE
copy plots kinda useless

### ISSUE THREAD

**Issue by preto677** [kostya12071/chia#2]
since, it will copy only already existing plots, and won't copy newly created.. It's hard to call that 'autmation' if I have to restart copy script manually

**Comment by kostya12071** [comment]
Copy script (chia2drive.ps1) checks for any new plot files every 15 minutes and will copy them.  There is a  /MOT:15 parameter that does that.  Please take a closer look.

**Comment by preto677** [comment]
seems to be working now

when I tried it for the first time, I had 2 done plots (that were moved successfully) in a folder + 1 plot.tmp.. and after plot.tmp was done saving, the script somehow did not detect it and console was saying   **"Monitor : waiting for 15 minutes and 1 changes..."** and in second line **"80 mins : 0 changes"**, so it actualy counted way beyond 15mins..

but ok, it works atm 👍
