### ISSUE TITLE
All farmers started....then nothing happens

### ISSUE THREAD

**Issue by brianwfreeman** [kostya12071/chia#5]
When I run the ps1 from PowerShell it says all Farmers started but then nothing happens. My temp drive is not populated, new windows are not opened.  

I am running as Administrator.

**Comment by brianwfreeman** [comment]
```
.\startPlottingAll.ps1 c:\temp d:\ 5 40
Starting process for Farmer 0...
Starting process for Farmer 1...
Starting process for Farmer 2...
Starting process for Farmer 3...
Starting process for Farmer 4...
All Farmers started. Can close this window
PS C:\Users\brian\Downloads>
```

**Comment by spencerbachus** [comment]
Me! Totally stuck

**Comment by kostya12071** [comment]
Hi Brian. Make sure your version of Chia is 1.1.5 or it's the same as in the .\startPlottingAll.ps1.  You should have a number of new PowerShell windows created in minimized state.  Temp drive would only populate with plot 0, plot 1 will start in 40 minutes. see if c:\temp\P0 folder is created.
